export const SKILL_OPTIONS = [
  'React',
  'React Native',
  'Next.js',
  'Node.js',
  'Express.js',
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'SQL',
  'MongoDB',
  'Supabase',
  'Firebase',
  'Tailwind CSS',
  'HTML',
  'CSS',
  'Git',
  'GitHub',
  'REST API',
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'OpenCV',
  'NLP',
  'Figma',
  'UI/UX',
  'Cybersecurity',
  'Docker',
  'AWS',
  'Azure'
]

export const INTEREST_OPTIONS = [
  'Healthcare',
  'Education',
  'Finance',
  'Agriculture',
  'E-commerce',
  'Gaming',
  'Productivity',
  'Fitness',
  'Food Delivery',
  'Travel',
  'Social Media',
  'Cybersecurity',
  'AI Tools',
  'Student Projects',
  'Job Search',
  'Resume Building',
  'Placement Preparation',
  'Business',
  'Startups',
  'Environment',
  'Smart Cities',
  'IoT',
  'Blockchain'
]